# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easytz.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimezoneStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default=easytz.models.get_default_timezone, max_length=48)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timezone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
